export interface SeedCategory {
  id: string;
  name: string;
  type: 'cultural' | 'sports_boys' | 'sports_girls';
  description: string;
  display_order: number;
  icon_name: string;
  color_scheme: string;
}

export interface SeedEvent {
  id: string;
  slug: string;
  category_id: string;
  category_name: string;
  name: string;
  type: 'cultural' | 'sports_boys' | 'sports_girls';
  tagline: string;
  short_description: string;
  description: string;
  rules: string[];
  venue: string;
  schedule_date: string;
  start_time: string;
  end_time: string;
  registration_type: 'individual' | 'team';
  min_team_size: number;
  max_team_size: number;
  team_size_label: string;
  gender: 'all' | 'boys' | 'girls';
  is_active: number;
  is_registration_open: number;
  registration_deadline: string;
  requires_audio: number;
}

export const defaultDeadline = '2026-10-15T23:59:59.000Z';

export const seedCategories: SeedCategory[] = [
  {
    id: 'dance',
    name: 'Dance',
    type: 'cultural',
    description: 'Electrifying western choreography, classical heritage, and contemporary sync on the RVRJC OAT stage.',
    display_order: 1,
    icon_name: 'Flame',
    color_scheme: 'from-purple-600 to-pink-600',
  },
  {
    id: 'music',
    name: 'Music & Band',
    type: 'cultural',
    description: 'Acoustic melodies, powerhouse solo vocals, and high-voltage live Battle of the Bands.',
    display_order: 2,
    icon_name: 'Music',
    color_scheme: 'from-indigo-600 to-purple-600',
  },
  {
    id: 'fine-arts',
    name: 'Fine Arts',
    type: 'cultural',
    description: 'Live canvas storytelling, graffiti spray art, sketching, and expressive visual creativity.',
    display_order: 3,
    icon_name: 'Palette',
    color_scheme: 'from-pink-600 to-rose-500',
  },
  {
    id: 'choreoday',
    name: 'Choreoday',
    type: 'cultural',
    description: 'Grand scale collegiate mega-troupe choreography and cinematic musical storytelling.',
    display_order: 4,
    icon_name: 'Users',
    color_scheme: 'from-amber-500 to-orange-600',
  },
  {
    id: 'dramatics',
    name: 'Dramatics',
    type: 'cultural',
    description: 'High-impact street plays (Nukkad Natak), stage proscenium drama, and monoacting.',
    display_order: 5,
    icon_name: 'Mask',
    color_scheme: 'from-red-600 to-amber-600',
  },
  {
    id: 'fashion',
    name: 'Fashion Show',
    type: 'cultural',
    description: 'High fashion runway choreography, ethnic glamour, and contemporary couture walk.',
    display_order: 6,
    icon_name: 'Sparkles',
    color_scheme: 'from-fuchsia-600 to-pink-500',
  },
  {
    id: 'tekraft',
    name: 'Tekraft Events',
    type: 'cultural',
    description: 'Techno-creative digital design, UI/UX sprints, digital poster blitz, and creative hack demos.',
    display_order: 7,
    icon_name: 'Cpu',
    color_scheme: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'literary',
    name: 'Literary',
    type: 'cultural',
    description: 'Slam poetry, elocution eloquence, and fiery parliamentary debate showdowns.',
    display_order: 8,
    icon_name: 'BookOpen',
    color_scheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'boys-sports',
    name: 'Boys Sports',
    type: 'sports_boys',
    description: 'National-level inter-collegiate outdoor and indoor athletic competitions for boys.',
    display_order: 9,
    icon_name: 'Trophy',
    color_scheme: 'from-orange-600 to-red-600',
  },
  {
    id: 'girls-sports',
    name: 'Girls Sports',
    type: 'sports_girls',
    description: 'High-intensity women championship matches spanning Throwball, Volleyball, and Table Tennis.',
    display_order: 10,
    icon_name: 'Trophy',
    color_scheme: 'from-cyan-500 to-blue-600',
  },
];

export const seedEvents: SeedEvent[] = [
  // ── Dance ──
  {
    id: 'western-group-dance',
    slug: 'western-group-dance',
    category_id: 'dance',
    category_name: 'Dance',
    name: 'Western Group Dance',
    type: 'cultural',
    tagline: 'High-octane synchronization & beat drops',
    short_description: 'Showcase team synergy, energetic transitions, and dynamic formations under the open-air stage lights.',
    description: 'The flagship group dance championship of COLORIDO 2K26. Teams battle across hip-hop, contemporary, jazz, popping, and freestyle routines before a live amphitheatre jury.',
    rules: [
      'Performance time: 6 to 8 minutes (max 10 minutes including stage clearance).',
      'Audio track must be submitted in MP3/WAV format during online registration or at reporting.',
      'Team size: 6 to 15 members on stage.',
      'No hazardous materials, fire, or liquid spills permitted on stage.',
      'Judging criteria: choreography, synchronization, musicality, and stage presence.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-26',
    start_time: '18:00',
    end_time: '21:00',
    registration_type: 'team',
    min_team_size: 6,
    max_team_size: 15,
    team_size_label: '6 - 15 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 1,
  },
  {
    id: 'classical-solo-dance',
    slug: 'classical-solo-dance',
    category_id: 'dance',
    category_name: 'Dance',
    name: 'Classical / Folk Solo',
    type: 'cultural',
    tagline: 'Grace, Natya & Traditional Expressions',
    short_description: 'Celebrate Indian heritage through Bharatnatyam, Kuchipudi, Kathak, or authentic folk expressions.',
    description: 'A solo classical showcase judging Bhava, Raga, Tala, and authentic traditional mudras and postures.',
    rules: [
      'Duration: 4 to 6 minutes.',
      'Classical or authentic traditional folk forms only.',
      'Audio accompaniment track must be uploaded in MP3/WAV format.',
      'Traditional costume appropriate for the chosen form is mandatory.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-26',
    start_time: '15:00',
    end_time: '17:30',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 1,
    team_size_label: 'Individual Solo',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 1,
  },

  // ── Music & Band ──
  {
    id: 'battle-of-bands',
    slug: 'battle-of-bands',
    category_id: 'music',
    category_name: 'Music & Band',
    name: 'Battle of the Bands',
    type: 'cultural',
    tagline: 'Live electric amplifiers and heart-thumping beats',
    short_description: 'Unleash rock, fusion, metal, or pop arrangements in front of a thunderous amphitheatre crowd.',
    description: 'The ultimate live instrumental battle. Standard drum kit and stage P.A. provided; bands bring their own guitars, processors, keyboards, and sticks.',
    rules: [
      'Total slot: 15 minutes (10 minutes live performance + 5 minutes soundcheck/setup).',
      'Team size: 3 to 8 members.',
      'Pre-recorded vocal backing tracks are strictly prohibited; live playing only.',
      'Demo audio track / setlist can be uploaded during registration.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-27',
    start_time: '17:00',
    end_time: '20:30',
    registration_type: 'team',
    min_team_size: 3,
    max_team_size: 8,
    team_size_label: '3 - 8 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 1,
  },
  {
    id: 'solo-vocals',
    slug: 'solo-vocals',
    category_id: 'music',
    category_name: 'Music & Band',
    name: 'Solo Vocals (Western / Eastern)',
    type: 'cultural',
    tagline: 'Melody, Pitch & Pitch-perfect resonance',
    short_description: 'Individual singing showcase across classical, film, indie, or Western pop categories.',
    description: 'Display pitch accuracy, breath control, voice modulation, and stage presence with either karaoke or one acoustic accompanist.',
    rules: [
      'Performance duration: 3 to 5 minutes.',
      'One karaoke track OR one acoustic accompanist permitted.',
      'Upload karaoke audio track during registration (MP3/WAV).',
      'Judged on pitch, rhythm, diction, and vocal range.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-26',
    start_time: '11:00',
    end_time: '14:00',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 1,
    team_size_label: 'Individual Solo',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 1,
  },

  // ── Fine Arts ──
  {
    id: 'live-canvas-painting',
    slug: 'live-canvas-painting',
    category_id: 'fine-arts',
    category_name: 'Fine Arts',
    name: 'Live Canvas Painting',
    type: 'cultural',
    tagline: 'Brush strokes inspired by festival themes',
    short_description: 'Create an original artistic painting on canvas based on the live theme announced on the spot.',
    description: 'Immerse in acrylic, oil, or watercolor on canvas. Themes announced 15 minutes before the clock starts.',
    rules: [
      'Duration: 2 hours.',
      'Standard canvas sheet will be provided by organizers.',
      'Participants must bring their own colors, brushes, and palettes.',
      'Evaluation criteria: creativity, thematic relevance, color harmony, and technique.',
    ],
    venue: 'RVRJC Open Air Theatre Concourse',
    schedule_date: '2026-02-26',
    start_time: '10:00',
    end_time: '12:00',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 2,
    team_size_label: 'Solo or Duo',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },
  {
    id: 'graffiti-street-art',
    slug: 'graffiti-street-art',
    category_id: 'fine-arts',
    category_name: 'Fine Arts',
    name: 'Graffiti & Poster Art',
    type: 'cultural',
    tagline: 'Bold typography, expressive spray & vibrant palettes',
    short_description: 'Express bold messages and vibrant street art visuals on designated display boards.',
    description: 'Urban street art competition combining lettering, stencils, and spray/acrylic techniques on giant panels.',
    rules: [
      'Duration: 2.5 hours.',
      'Display boards provided by college.',
      'Team of 2 to 3 artists.',
      'Offensive or politically controversial content leads to instant disqualification.',
    ],
    venue: 'RVRJC Open Air Theatre Concourse',
    schedule_date: '2026-02-27',
    start_time: '10:30',
    end_time: '13:00',
    registration_type: 'team',
    min_team_size: 2,
    max_team_size: 3,
    team_size_label: '2 - 3 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },

  // ── Choreoday ──
  {
    id: 'choreoday-mega-group',
    slug: 'choreoday-mega-group',
    category_id: 'choreoday',
    category_name: 'Choreoday',
    name: 'Choreoday Mega Troupe Showcase',
    type: 'cultural',
    tagline: 'Grand collegiate ensemble choreography & narrative visual spectacle',
    short_description: 'Massive synchrony, rapid costume changes, and theatrical dance narratives by collegiate dance societies.',
    description: 'The centerpiece collegiate dance trophy of the festival. Teams of 10 to 25 dancers present a comprehensive themed production under festival spotlights.',
    rules: [
      'Performance duration: 8 to 12 minutes.',
      'Team size: 10 to 25 members.',
      'Master audio track must be uploaded in MP3 or WAV format during registration.',
      'Props allowed with prior approval from the stage coordinator.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-27',
    start_time: '18:30',
    end_time: '21:30',
    registration_type: 'team',
    min_team_size: 10,
    max_team_size: 25,
    team_size_label: '10 - 25 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 1,
  },

  // ── Dramatics ──
  {
    id: 'nukkad-natak',
    slug: 'nukkad-natak',
    category_id: 'dramatics',
    category_name: 'Dramatics',
    name: 'Street Play (Nukkad Natak)',
    type: 'cultural',
    tagline: 'Thunderous dafli beats, high voice projection & social awakening',
    short_description: 'Ring of spectators, live acoustic percussion, and powerful satirical social messaging.',
    description: 'Traditional open-air Indian street theatre performed in a 360-degree spectator circle with dholak, dafli, and choral choruses.',
    rules: [
      'Performance duration: 12 to 15 minutes.',
      'Team size: 8 to 20 members.',
      'Live acoustic instruments only (no electronic amplification).',
      'Judged on social script, voice clarity, audience engagement, and choral discipline.',
    ],
    venue: 'Playground in front of SJB Block',
    schedule_date: '2026-02-26',
    start_time: '14:00',
    end_time: '17:00',
    registration_type: 'team',
    min_team_size: 8,
    max_team_size: 20,
    team_size_label: '8 - 20 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },

  // ── Fashion Show ──
  {
    id: 'campus-couture-vogue',
    slug: 'campus-couture-vogue',
    category_id: 'fashion',
    category_name: 'Fashion Show',
    name: 'Campus Couture Vogue Walk',
    type: 'cultural',
    tagline: 'Avant-garde styling, runway grace & charismatic presence',
    short_description: 'Thematic college runway teams presenting innovative fashion, poise, and choreography.',
    description: 'A dazzling thematic runway presentation. Collegiate teams interpret futuristic, ethnic, or sustainable design themes.',
    rules: [
      'Performance slot: 10 to 12 minutes.',
      'Team size: 8 to 16 models including designers/stylists.',
      'Runway music track must be uploaded in MP3/WAV format.',
      'Costumes must adhere to decent college event standards.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-27',
    start_time: '19:30',
    end_time: '22:00',
    registration_type: 'team',
    min_team_size: 8,
    max_team_size: 16,
    team_size_label: '8 - 16 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 1,
  },

  // ── Tekraft Events ──
  {
    id: 'tekraft-digital-blitz',
    slug: 'tekraft-digital-blitz',
    category_id: 'tekraft',
    category_name: 'Tekraft Events',
    name: 'Tekraft Digital Creative Blitz',
    type: 'cultural',
    tagline: 'Interactive UI showcase, digital aesthetics & creative tech',
    short_description: 'Combine software engineering with digital art, dynamic animations, and interactive creativity.',
    description: 'Fast-paced creative technology challenge where students design interactive web art, procedural visuals, or creative applications live.',
    rules: [
      'Duration: 3 hours live sprint.',
      'Team size: 1 to 3 members.',
      'Submissions judged on aesthetics, technical creativity, responsiveness, and uniqueness.',
    ],
    venue: 'RVRJC Computer Center Complex',
    schedule_date: '2026-02-26',
    start_time: '10:00',
    end_time: '13:00',
    registration_type: 'team',
    min_team_size: 1,
    max_team_size: 3,
    team_size_label: '1 - 3 Members',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },

  // ── Literary ──
  {
    id: 'slam-poetry',
    slug: 'slam-poetry',
    category_id: 'literary',
    category_name: 'Literary',
    name: 'Slam Poetry & Spoken Word',
    type: 'cultural',
    tagline: 'Raw emotion, rhythmic cadence & spoken eloquence',
    short_description: 'Take the podium with your original poetry. Move hearts and minds with pure expressive cadence.',
    description: 'Solo spoken word competition in English or Telugu. No props or costumes; voice, words, and emotive cadence only.',
    rules: [
      'Time limit: 3 to 4 minutes.',
      'Original compositions only; plagiarism leads to immediate disqualification.',
      'Judged on content, performance delivery, rhythm, and emotional resonance.',
    ],
    venue: 'RVRJC Open Air Theatre (OAT)',
    schedule_date: '2026-02-26',
    start_time: '14:00',
    end_time: '16:00',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 1,
    team_size_label: 'Individual Solo',
    gender: 'all',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },

  // ── Boys Sports ──
  {
    id: 'basketball-boys',
    slug: 'basketball-boys',
    category_id: 'boys-sports',
    category_name: 'Boys Sports',
    name: 'Basketball Championship (Boys)',
    type: 'sports_boys',
    tagline: 'High press, fast breaks & rim-rattling dunks',
    short_description: 'Inter-collegiate 5v5 full-court basketball tournament under floodlights.',
    description: 'Full court FIBA regulation play on high-grip acrylic surface with electronic scoreboards and professional referees.',
    rules: [
      'Team: 5 Playing + 5 Substitutes (Total 10).',
      'Four quarters of 8 minutes running clock.',
      'FIBA competition rules apply.',
    ],
    venue: 'Basketball Court inside campus',
    schedule_date: '2026-02-26',
    start_time: '15:00',
    end_time: '19:00',
    registration_type: 'team',
    min_team_size: 5,
    max_team_size: 10,
    team_size_label: '5 - 10 Players',
    gender: 'boys',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },
  {
    id: 'volleyball-boys',
    slug: 'volleyball-boys',
    category_id: 'boys-sports',
    category_name: 'Boys Sports',
    name: 'Volleyball Championship (Boys)',
    type: 'sports_boys',
    tagline: 'Powerful spikes, monster blocks & court agility',
    short_description: 'Knockout volleyball tournament played on championship court with viewing gallery.',
    description: 'Best of 3 sets up to 25 points, rally scoring system under VFI guidelines.',
    rules: [
      'Squad: 6 Playing + 6 Substitutes (Max 12).',
      'Rally point system, best of 3 sets (25, 25, 15).',
      'Official college team jerseys mandatory.',
    ],
    venue: 'Playground in front of SJB Block',
    schedule_date: '2026-02-26',
    start_time: '10:00',
    end_time: '16:00',
    registration_type: 'team',
    min_team_size: 6,
    max_team_size: 12,
    team_size_label: '6 - 12 Players',
    gender: 'boys',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },
  {
    id: 'table-tennis-boys',
    slug: 'table-tennis-boys',
    category_id: 'boys-sports',
    category_name: 'Boys Sports',
    name: 'Table Tennis Championship (Boys)',
    type: 'sports_boys',
    tagline: 'Lightning spin, quick reflex returns & precision placement',
    short_description: 'Indoor table tennis tournament on Stiga tournament boards inside the sports pavilion.',
    description: 'Singles and team rubber format played under ITTF rules on anti-glare indoor courts.',
    rules: [
      'Individual solo entry.',
      'Best of 5 sets, 11 points each set.',
      'ITTF approved rubber paddles only.',
    ],
    venue: 'Sports Plex in front of Canteen',
    schedule_date: '2026-02-27',
    start_time: '10:00',
    end_time: '15:00',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 1,
    team_size_label: 'Individual Solo',
    gender: 'boys',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },

  // ── Girls Sports ──
  {
    id: 'throwball-girls',
    slug: 'throwball-girls',
    category_id: 'girls-sports',
    category_name: 'Girls Sports',
    name: 'Throwball Championship (Girls)',
    type: 'sports_girls',
    tagline: 'Velocity throws, quick reaction catches & teamwork',
    short_description: 'Premier inter-collegiate throwball tournament on competition outdoor courts.',
    description: 'Fast-paced women throwball tournament conducted under Throwball Federation of India guidelines.',
    rules: [
      'Squad: 7 Playing + 5 Substitutes (Max 12).',
      'Best of 3 sets to 25 points.',
      'Two-handed catch and one-handed throw within 3 seconds.',
    ],
    venue: 'Playground in front of SJB Block',
    schedule_date: '2026-02-26',
    start_time: '10:00',
    end_time: '15:30',
    registration_type: 'team',
    min_team_size: 7,
    max_team_size: 12,
    team_size_label: '7 - 12 Players',
    gender: 'girls',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },
  {
    id: 'tennikoit-girls',
    slug: 'tennikoit-girls',
    category_id: 'girls-sports',
    category_name: 'Girls Sports',
    name: 'Tennikoit Tournament (Girls)',
    type: 'sports_girls',
    tagline: 'Swift ring catch, aerial spin & court agility',
    short_description: 'Singles and doubles tennikoit competition hosted inside the sports pavilion.',
    description: 'Precision ring sport challenging speed, trajectory anticipation, and reflex catching.',
    rules: [
      'Singles format.',
      'Best of 3 sets to 21 points.',
      'Straight release without wobble or body contact.',
    ],
    venue: 'Sports Plex in front of Canteen',
    schedule_date: '2026-02-26',
    start_time: '11:00',
    end_time: '15:00',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 1,
    team_size_label: 'Individual Solo',
    gender: 'girls',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },
  {
    id: 'table-tennis-girls',
    slug: 'table-tennis-girls',
    category_id: 'girls-sports',
    category_name: 'Girls Sports',
    name: 'Table Tennis Championship (Girls)',
    type: 'sports_girls',
    tagline: 'Rapid smashes, deceptive spin & flawless counter-attacks',
    short_description: 'Indoor table tennis singles championship on competition boards inside the pavilion.',
    description: 'Fast reflex rallies on international standard ITTF boards under glare-free lighting.',
    rules: [
      'Individual solo entry.',
      'Best of 5 sets, 11 points each set.',
      'Standard paddle and ball specifications.',
    ],
    venue: 'Sports Plex in front of Canteen',
    schedule_date: '2026-02-27',
    start_time: '11:00',
    end_time: '15:30',
    registration_type: 'individual',
    min_team_size: 1,
    max_team_size: 1,
    team_size_label: 'Individual Solo',
    gender: 'girls',
    is_active: 1,
    is_registration_open: 1,
    registration_deadline: defaultDeadline,
    requires_audio: 0,
  },
];
